export const SCHEDULE_REQUEST = "SCHEDULE_REQUEST";
export const SCHEDULE_SUCCESS = "SCHEDULE_SUCCESS";
export const SCHEDULE_FAILED = "SCHEDULE_FAILED";
export const SCHEDULE_REMOVE = "SCHEDULE_REMOVE";