export const BUTTON_REQUEST = "BUTTON_REQUEST";
export const BUTTON_SUCCESS = "BUTTON_SUCCESS";
export const BUTTON_FAILED = "BUTTON_FAILED";

export const FEATURE_CREATE_LOADING = "FEATURE_CREATE_LOADING";
export const FEATURE_CREATE_SUCCESS = "FEATURE_CREATE_SUCCESS";
export const FEATURE_CREATE_FAILED = "FEATURE_CREATE_FAILED";
