export const FINAL_SUBMITTED_DATA_REQUEST = "FINAL_SUBMITTED_DATA_REQUEST";
export const FINAL_SUBMITTED_DATA_SUCCESS = "FINAL_SUBMITTED_DATA_SUCCESS";
export const FINAL_SUBMITTED_DATA_FAILED = "FINAL_SUBMITTED_DATA_FAILED";