export const PROPERTY_REQUEST = "PROPERTY_REQUEST";
export const PROPERTY_SUCCESS = "PROPERTY_SUCCESS";
export const PROPERTY_FAILED = "PROPERTY_FAILED";
export const PROPERTY_REMOVE = "PROPERTY_REMOVE";
// export const PROPERTY_PROPOSAL_REMOVE = "PROPERTY_PROPOSAL_REMOVE";
