export const NOTIFICATION_COUNT_REQUEST = 'NOTIFICATION_COUNT_REQUEST'
export const NOTIFICATION_COUNT_SUCCESS = 'NOTIFICATION_COUNT_SUCCESS'
export const NOTIFICATION_COUNT_FAILED = 'NOTIFICATION_COUNT_FAILED'
export const NOTIFICATION_ADD_COUNT = 'NOTIFICATION_ADD_COUNT'
