export const UPLOAD_CERTIFICATE_REQUEST = "UPLOAD_CERTIFICATE_REQUEST";
export const UPLOAD_CERTIFICATE_SUCCESS = "UPLOAD_CERTIFICATE_SUCCESS";
export const UPLOAD_CERTIFICATE_FAILED = "UPLOAD_CERTIFICATE_FAILED";