export const REQUIRE_CERTIFICATE_REQUEST = 'REQUIRE_CERTIFICATE_REQUEST'
export const REQUIRE_CERTIFICATE_SUCCESS = 'REQUIRE_CERTIFICATE_SUCCESS'
export const REQUIRE_CERTIFICATE_FAILED = 'REQUIRE_CERTIFICATE_FAILED'
export const CERTIFICATE_REMOVE = 'CERTIFICATE_REMOVE'
