import Navbar from "../src/component/shared/Navbar/Navbar";
import Head from "next/head";
import {
  Box,
  Grid,
  Typography,
  Container,
  ImageList,
  ImageListItem,
  Button,
  InputBase,
  Paper,
  Tabs,
  Tab,
  Divider,
  Stack,
  Pagination,
} from "@mui/material";
import orionImage from "../public/Images/orion_view.svg";
import Image from "next/image";
import TabView from "../src/component/PropertyView/tab/TabView";
import AmountView from "../src/component/PropertyView/amount/AmountView";
import Features from "../src/component/PropertyView/feature/Features";
import AboutProperty from "../src/component/PropertyView/AboutProperty/AboutProperty";
import Negotiate from "../src/component/PropertyView/Negotiate/Negotiate";
import HouseCard from "../src/component/reuseable/HouseCard/HouseCard";
import Footer from "../src/component/shared/Footer/Footer";
import SliderView from "../src/component/PropertyView/slider/SliderView";
import SlideImage from "../src/component/PropertyView/slideImage/SlideImage";
import SliderViewMobile from "../src/component/PropertyView/SliderViewMobile/SliderViewMobile";
import sliderView from "../public/Images/sliderView.png";
import sliderViewSmall from "../public/Images/sliderViewSmall.png";
import BaseModal from "../src/component/reuseable/baseModal/BaseModal";
import ProposalModal from "../src/component/PropertyView/ProposalStepperComponent/ProposalModal";
import { useState } from "react";
import BlogCardUpper from "../src/component/blog/blogCardUpper/BlogCardUpper";
import BlogHighlightsCard from "../src/component/blog/blogHighlightsCard/BlogHighlightsCard";
import SmallBlogCard from "../src/component/blog/smallBlogCard/SmallBlogCard";
import MostAccess from "../src/component/blog/mostAccessed/MostAccess";

const aboutProperty = [
  "Heater",
  "Dependency",
  "Balcony",
  "Service area",
  "Air conditioner",
  "Source",
  "Coif",
  "Cabinets",
  "Wardrobe",
  "Stove",
];

const aboutCondo = [
  "sports court",
  "playground",
  "Electric fence",
  "Internal TV circuit",
  "Ordinance",
  "individual gas",
  "service entrance",
  "Service elevator",
  "Employee locker room",
  "Academy",
  "heated pool",
  "Party room",
];

const surroundings = [
  "hospitals",
  "pharmacies",
  "Markets",
  "Laundries",
  "Museum",
];

export default function PropertyView(props) {
  //add_proposal_modal
  const [proposalOpen, setProposalOpen] = useState(false);
  const handleProposalOpen = () => setProposalOpen(true);
  const handleProposalClose = () => setProposalOpen(false);

  const [value, setValue] = useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Navbar shape={false} paddingY={"1vh"} />
        <Grid
          container
          direction="column"
          justifyContent="center"
          alignItems="center"
          sx={{
            height: "60vh",
            background: "linear-gradient(90deg, #20BAF6 0%, #7450F0 100%)",
          }}
        >
          <Typography
            variant="p"
            sx={{
              fontSize: {
                xs: "24px",
                sm: "24px",
                md: "24px",
                lg: "32px",
                xl: "32px",
              },
              fontWeight: {
                xs: "700",
                sm: "700",
                md: "700",
                lg: "800",
                xl: "800",
              },
              px: { xs: 2, sm: 2, md: 0, lg: 0, xl: 0 },
              textAlign: "center",
              lineHeight: "38px",
              color: "#ffffff",
            }}
          >
            All about Lokkan and the real estate market
          </Typography>
          <Typography
            variant="p"
            sx={{
              px: { xs: 2, sm: 2, md: 0, lg: 0, xl: 0 },
              fontSize: "16px",
              fontWeight: "600",
              lineHeight: "19px",
              color: "#ffffff",
              marginTop: 2,
            }}
          >
            Subscribe to our newsletter!
          </Typography>

          <Paper
            component="form"
            sx={{
              mt: 2,
              display: "flex",
              alignItems: "center",
              // border: "1px solid red",
              boxShadow: "none",
              //   border: "1px solid #D3D3DF",
              borderRadius: "4px",
              width: {
                xs: "90%",
                sm: "90%",
                md: "70%",
                xl: "30%",
                lg: "30%",
              },
              mx: { xs: 2, sm: 2, md: 0, lg: 0, xl: 0 },
            }}
          >
            <Grid sx={{ paddingRight: 2, width: "100%" }}>
              <InputBase
                fullWidth
                sx={{ ml: 1, flex: 1 }}
                placeholder="Email"
                inputProps={{
                  "aria-label": "search google maps",
                  style: {
                    color: "#9F9FA9",
                    fontSize: "20px",
                  },
                }}
              />
            </Grid>
            <Box
              sx={{
                backgroundColor: "#00C1B4",
                padding: "1vh",
                borderRadius: "0px 4px 4px 0px",
                boxShadow: "0px 4px 34px rgba(0, 0, 0, 0.08)",

                width: {
                  xs: "35%",
                  sm: "25%",
                  md: "15%",
                  lg: "30%",
                  xl: "30%",
                },
                textAlign: "center",
              }}
            >
              To send
            </Box>
          </Paper>

          <Box
            sx={{ maxWidth: { xs: 320, sm: 480, md: 500, lg: 1000, xl: 1200 } }}
          >
            <Tabs
              onChange={handleChange}
              aria-label="basic tabs example"
              sx={{
                mt: 5,
              }}
              variant="scrollable"
              value={value}
              TabIndicatorProps={{
                style: {
                  backgroundColor: "#ffffff",
                },
              }}
            >
              <Tab
                sx={{
                  "&.Mui-selected": {
                    borderBottom: "1px solid #fffff",
                    color: "#ffffff",
                  },
                  fontSize: `${value === 0 ? "18px" : "16px"}`,
                  color: "#ffffff",
                  fontWeight: `${value === 0 ? "800" : "600"}`,
                  px: 3,
                  py: 2,
                  mr: 4,
                  textTransform: "none",
                  width: `${value === 0 ? "20vh" : "20vh"}`,

                  border: `${value === 0 ? " 2px solid #FFFFFF" : ""}`,
                  borderRadius: `${value === 0 ? "4px" : ""}`,
                }}
                label="All"
              />
              <Tab
                sx={{
                  "&.Mui-selected": {
                    borderBottom: "1px solid #fffff",
                    color: "#ffffff",
                  },
                  fontSize: `${value === 1 ? "18px" : "16px"}`,
                  color: "#ffffff",
                  fontWeight: `${value === 1 ? "800" : "600"}`,
                  px: 3,
                  py: 2,
                  mr: 4,
                  textTransform: "none",
                  width: `${value === 1 ? "20vh" : "20vh"}`,

                  border: `${value === 1 ? " 2px solid #FFFFFF" : ""}`,
                  borderRadius: `${value === 1 ? "4px" : ""}`,
                }}
                label="Category"
              />
              <Tab
                sx={{
                  "&.Mui-selected": {
                    borderBottom: "1px solid #fffff",
                    color: "#ffffff",
                  },
                  fontSize: `${value === 2 ? "18px" : "16px"}`,
                  color: "#ffffff",
                  fontWeight: `${value === 2 ? "800" : "600"}`,
                  px: 3,
                  py: 2,
                  mr: 4,
                  textTransform: "none",
                  width: `${value === 2 ? "20vh" : "20vh"}`,

                  border: `${value === 2 ? " 2px solid #FFFFFF" : ""}`,
                  borderRadius: `${value === 2 ? "4px" : ""}`,
                }}
                label="Category"
              />
              <Tab
                sx={{
                  "&.Mui-selected": {
                    borderBottom: "1px solid #fffff",
                    color: "#ffffff",
                  },
                  fontSize: `${value === 3 ? "18px" : "16px"}`,
                  color: "#ffffff",
                  fontWeight: `${value === 3 ? "800" : "600"}`,
                  px: 3,
                  py: 2,
                  mr: 4,
                  textTransform: "none",
                  width: `${value === 3 ? "20vh" : "20vh"}`,

                  border: `${value === 3 ? " 2px solid #FFFFFF" : ""}`,
                  borderRadius: `${value === 3 ? "4px" : ""}`,
                }}
                label="Category"
              />
              <Tab
                sx={{
                  "&.Mui-selected": {
                    borderBottom: "1px solid #fffff",
                    color: "#ffffff",
                  },
                  fontSize: `${value === 4 ? "18px" : "16px"}`,
                  color: "#ffffff",
                  fontWeight: `${value === 4 ? "800" : "600"}`,
                  px: 3,
                  py: 2,
                  mr: 4,
                  textTransform: "none",
                  width: `${value === 4 ? "20vh" : "20vh"}`,

                  border: `${value === 4 ? " 2px solid #FFFFFF" : ""}`,
                  borderRadius: `${value === 4 ? "4px" : ""}`,
                }}
                label="Category"
              />
              <Tab
                sx={{
                  "&.Mui-selected": {
                    borderBottom: "1px solid #fffff",
                    color: "#ffffff",
                  },
                  fontSize: `${value === 5 ? "18px" : "16px"}`,
                  color: "#ffffff",
                  fontWeight: `${value === 5 ? "800" : "600"}`,
                  px: 3,
                  py: 2,
                  mr: 4,
                  textTransform: "none",
                  width: `${value === 5 ? "20vh" : "20vh"}`,

                  border: `${value === 5 ? " 2px solid #FFFFFF" : ""}`,
                  borderRadius: `${value === 5 ? "4px" : ""}`,
                }}
                label="Category"
              />
            </Tabs>
          </Box>
          <Box
            sx={{
              position: "absolute",
            }}
          ></Box>
        </Grid>

        <Box
          sx={{
            px: 25,
            position: "relative",
            top: -60,
          }}
        >
          <BlogCardUpper />
        </Box>

        <Box sx={{ mb: 2, px: 2 }}>
          <Typography
            variant="p"
            sx={{
              fontSize: "12px",
              fontWeight: "400",
              lineHeight: "28px",
              color: "#7450F0",
            }}
          >
            Highlights
          </Typography>
          <Divider sx={{ color: "#D3D3DF" }} />
        </Box>
        <Box sx={{ mx: 2, mb: 4 }}>
          <Grid container spacing={1}>
            {[0, 1, 2].map((data, index) => (
              <Grid item xs={12} sm={12} md={12} lg={4} xl={4} key={index}>
                <BlogHighlightsCard />
              </Grid>
            ))}
          </Grid>
        </Box>
        <Box sx={{ mb: 2, px: 2 }}>
          <Divider sx={{ color: "#D3D3DF" }} />
        </Box>
        <Grid
          container
          spacing={1}
          sx={{ mt: 2, pl: { xs: 1, sm: 2, md: 2, lg: 2, xl: 2 } }}
        >
          <Grid item xs={12} sm={12} md={12} lg={9} xl={9}>
            <Grid container spacing={1}>
              {[0, 1, 2, 3, 4, 5, 6, 7].map((data, index) => (
                <Grid key={index} item xs={12} sm={12} md={12} lg={6} xl={6}>
                  {/* <BlogCardUpper /> */}
                  <SmallBlogCard />
                </Grid>
              ))}
            </Grid>
          </Grid>
          <Grid item xs={12} sm={12} md={12} lg={3} xl={3}>
            <MostAccess />
          </Grid>
        </Grid>
        <Stack spacing={2} sx={{ marginY: 8 }}>
          <Pagination count={5} variant="outlined" shape="rounded" />
        </Stack>
        <Footer />
      </main>
    </div>
  );
}
