import Navbar from "../src/component/shared/Navbar/Navbar";
import Footer from "../src/component/shared/Footer/Footer";
import Head from "next/head";
import { Box, Tooltip } from "@mui/material";
import mobileGray from "../public/Images/mobileGray.png";
import brokerBackgroundImage from "../public/Images/brokerBackground.png";
import { useSession, signIn, signOut } from "next-auth/react";
import { _baseURL } from "../consts";
import { useEffect, useState } from "react";
import SetCookie from "@/hooks/setCookie";
import en from "locales/en";
import pt from "locales/pt";
import BaseModal from "@/component/reuseable/baseModal/BaseModal";
import KnowMoreContent from "@/component/home/knowMoreContent/KnowMoreContent";
import BrokerContent from "@/component/IAmBroker/BrokerContent/BrokerContent";
import KnowMoreContentBroker from "@/component/IAmBroker/knowMoreContentBroker/KnowMoreContentBroker";

export default function BrokerDetails({ language }) {
  const { data: session } = useSession();

  const [myValue, setMyValue] = useState(language || "pt");

  useEffect(() => {
    SetCookie("language", myValue);
  }, [myValue]);

  const t = myValue === "en" ? en : pt;

  return (
    <div>
      <Head>
        <title>Lokkan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/negotiate.png" />
      </Head>

      <main className="section">
        <Footer />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const cookies = context.req.cookies["language"] || "pt";

  return {
    props: { language: cookies }, // will be passed to the page component as props
  };
}
