import Navbar from "../src/component/shared/Navbar/Navbar";
import Footer from "../src/component/shared/Footer/Footer";
import shapeIcon from "../public/Images/eclipseShape.png";
import Head from "next/head";
import {
  Box,
  Grid,
  Typography,
  Container,
  ImageList,
  ImageListItem,
} from "@mui/material";
import FulfillDream from "../src/component/home/fullfill/FulfillDream";
import SideContent from "../src/component/home/FullfillSideContent/SideContent";
import SellSideContent from "../src/component/home/wantToSellSideContent/SellSideContent";
import mobileGray from "../public/Images/mobileGray.png";
import mobileBlue from "../public/Images/mobileBlue.png";
import WantSellSvgBackground from "../src/component/svg/WantSellSvgBackground";
import { renderToStaticMarkup } from "react-dom/server";
import WantToSell from "../src/component/home/wantToSell/WantToSell";
import BrokerRegisterContent from "../src/component/home/whoIsBroker/brokerRegister/BrokerRegisterContent";
import BrokerImageContent from "../src/component/home/whoIsBroker/brokerContent/BrokerImageContent";
import BestDealSvgBackground from "../src/component/svg/BestDealSvgBackground";
import HouseCard from "../src/component/reuseable/HouseCard/HouseCard";
import MobileSideContent from "../src/component/home/FullfillSideContent/mobileSideContent";
import BrokerImageContentMobile from "../src/component/home/whoIsBroker/brokerContent/BrokerImageContentMobile";
import BrokerHelp from "../src/component/IAmBroker/BrokerHelp/BrokerHelp";
import BrokerHelpContent from "../src/component/IAmBroker/BrokerHelp/BrokerHelpContent";
import BecomeBrokerContent from "../src/component/IAmBroker/BecomeBroker/BecomeBrokerContent";
import BecomeBroker from "../src/component/IAmBroker/BecomeBroker/BecomeBroker";
import CalulateComission from "../src/component/IAmBroker/MaxmizeResult/CalulateComission";
import ComissionResult from "../src/component/IAmBroker/MaxmizeResult/ComissionResult";
import BrokerFacilities from "../src/component/IAmBroker/BrokerFacilities/BrokerFacilities";

export default function Broker(props) {
  const svgString = encodeURIComponent(
    renderToStaticMarkup(<WantSellSvgBackground />)
  );
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Navbar shape={false} />
        <Grid
          container
          spacing={2}
          sx={{
            paddingRight: { xs: 5, sm: 5, md: 10, xl: 10, lg: 10 },
            marginTop: 2,
          }}
        >
          <Grid item xs={12} sm={12} md={12} xl={6} lg={6}>
            <BrokerHelp />
          </Grid>
          <Grid item xs={12} sm={12} md={12} xl={6} lg={6}>
            <BrokerHelpContent />
          </Grid>
        </Grid>
        <Box
          sx={{
            // backgroundColor: "#F9F9FB",
            paddingTop: { xs: 0, sm: 0, md: 10, lg: 10, xl: 10 },
            // paddingBottom: 5,
            // clipPath:
            //   "polygon(0 0, 13% 5%, 30% 10%, 53% 13%, 71% 10%, 100% 0, 100% 85%, 100% 100%, 85% 100%, 15% 100%, 0 100%, 0% 85%)",
            // clipPath: "circle(15em at 10% 40%)",
          }}
        >
          <Grid
            container
            direction="row"
            justifyContent="center"
            alignItems="center"
            sx={{
              mt: { xs: 8, sm: 8, md: 0, xl: 0, lg: 0 },
              pb: 5,
              px: { xs: "2.5vh", sm: "2.5vh" },
            }}
          >
            <Typography
              variant="p"
              sx={{
                fontSize: {
                  sm: "32px",
                  xs: "32px",
                  md: "40px",
                  lg: "40px",
                  xl: "40px",
                },
                pb: { xs: 2, sm: 2, md: 5, lg: 5, xl: 5 },
                color: "#1A1859",
                fontWeight: "800",
              }}
            >
              Become a super broker
            </Typography>
          </Grid>
          <Container
            maxWidth="lg"
            sx={{ mt: { xs: 8, sm: 8, md: 0, xl: 0, lg: 0 } }}
          >
            <Grid
              container
              spacing={2}

              // className="shape-circle"
            >
              <Grid item xs={12} sm={12} md={12} xl={6} lg={6}>
                <BecomeBrokerContent />
              </Grid>
              <Grid item xs={12} sm={12} md={12} xl={6} lg={6}>
                <BecomeBroker />
              </Grid>
            </Grid>
          </Container>
        </Box>
        <Box
          sx={{
            paddingTop: { xs: 5, sm: 5, md: 10, lg: 10, xl: 10 },
            paddingBottom: 10,

            backgroundImage: {
              xs: `url(${mobileGray.src})`,
              sm: `url(${mobileGray.src})`,
              md: `url("data:image/svg+xml,${svgString}")`,
              lg: `url("data:image/svg+xml,${svgString}")`,
              xl: `url("data:image/svg+xml,${svgString}")`,
            },
            backgroundRepeat: "no-repeat",
            backgroundSize: "cover",
          }}
        >
          <Grid
            container
            direction="row"
            justifyContent="center"
            alignItems="center"
            sx={{
              //   mt: { xs: 8, sm: 8, md: 0, xl: 0, lg: 0 },
              pb: { xs: 1, sm: 1, md: 5, xl: 5, lg: 5 },
              px: { xs: "2.5vh", sm: "2.5vh" },
            }}
          >
            <Typography
              variant="p"
              sx={{
                fontSize: {
                  sm: "32px",
                  xs: "32px",
                  md: "40px",
                  lg: "40px",
                  xl: "40px",
                },
                pb: { xs: 0, sm: 0, md: 5, xl: 5, lg: 5 },
                mt: { xs: 0, sm: 0, md: 10, xl: 10, lg: 10 },
                color: "#1A1859",
                fontWeight: "800",
              }}
            >
              Maximize your results
            </Typography>
          </Grid>
          <Container
            maxWidth="lg"
            sx={{
              //   mt: { xs: 8, sm: 8, md: 0, xl: 0, lg: 0 },
              background: "#FFFFFF",
              borderRadius: "6px",
              boxShadow: "0px 8px 24px rgba(3, 2, 39, 0.07)",
              py: 4,
            }}
          >
            <Grid
              container
              spacing={2}

              // className="shape-circle"
            >
              <Grid item xs={12} sm={12} md={12} xl={6} lg={6}>
                <CalulateComission />
              </Grid>
              <Grid item xs={12} sm={12} md={12} xl={6} lg={6}>
                <ComissionResult />
              </Grid>
            </Grid>
          </Container>

          <Container
            maxWidth="lg"
            sx={{ marginTop: { xs: 5, sm: 5, md: 15, xl: 15, lg: 15 } }}
          >
            <Grid container spacing={2}>
              {[0, 1, 2].map((data, index) => (
                <Grid key={index} item xs={12} sm={12} md={6} xl={4} lg={4}>
                  <BrokerFacilities
                    text={
                      "Work wherever you are and with flexible hours and total autonomy"
                    }
                  />
                </Grid>
              ))}
            </Grid>
          </Container>
          <Container maxWidth="lg" sx={{ marginTop: 5 }}>
            <Grid container spacing={2}>
              {[0, 1].map((data, index) => (
                <Grid key={index} item xs={12} sm={12} md={6} xl={6} lg={6}>
                  <BrokerFacilities
                    text={
                      "Get access to the property database, with third-party properties, launches by land developers, builders and developers in several cities"
                    }
                  />
                </Grid>
              ))}
            </Grid>
          </Container>
        </Box>
        <Footer />
      </main>
    </div>
  );
}
