import Navbar from "../src/component/shared/Navbar/Navbar";
import Footer from "../src/component/shared/Footer/Footer";

import Head from "next/head";
import {
  Box,
  Button,
  Container,
  Grid,
  Tooltip,
  Typography,
} from "@mui/material";
import BaseStepper from "../src/component/reuseable/baseStepper/BaseStepper";
import { Fragment, useState } from "react";
import PersonalData from "../src/component/brokerRegistration/personalData/PersonalData";
import AddressData from "../src/component/brokerRegistration/Address/AddressData";
import PerformanceData from "../src/component/brokerRegistration/performance/PerformanceData";
import Image from "next/image";
import stepFinish from "../public/Images/step_finish.png";
import BrokerRegistrationFooter from "../src/component/shared/Footer/BrokerRegistrationFooter";
import BaseModal from "../src/component/reuseable/baseModal/BaseModal";
import BrokerRegistrationSentModal from "../src/component/brokerRegistration/BrokerRegistrationSendModal/BrokerRegistrationSendModal";

const steps = ["Personal Data", "Address", "Performance"];

export default function BrokerRegistration({
  loginOpen,
  setLoginOpen,
  handleLoginOpen,
  handleLoginClose,
}) {
  const [activeStep, setActiveStep] = useState(0);
  const [skipped, setSkipped] = useState(new Set());

  const isStepOptional = (step) => {
    return step === 1;
  };

  const isStepSkipped = (step) => {
    return skipped.has(step);
  };

  const handleNext = () => {
    let newSkipped = skipped;
    if (isStepSkipped(activeStep)) {
      newSkipped = new Set(newSkipped.values());
      newSkipped.delete(activeStep);
    }

    setActiveStep((prevActiveStep) => prevActiveStep + 1);
    setSkipped(newSkipped);
  };

  const handleBack = () => {
    setActiveStep((prevActiveStep) => prevActiveStep - 1);
  };

  const handleSkip = () => {
    if (!isStepOptional(activeStep)) {
      // You probably want to guard against something like this,
      // it should never occur unless someone's actively trying to break something.
      throw new Error("You can't skip a step that isn't optional.");
    }

    setActiveStep((prevActiveStep) => prevActiveStep + 1);
    setSkipped((prevSkipped) => {
      const newSkipped = new Set(prevSkipped.values());
      newSkipped.add(activeStep);
      return newSkipped;
    });
  };

  const handleReset = () => {
    setActiveStep(0);
  };

  const [sentModalOpen, setSentModalOpen] = useState(false);
  const handleOpen = () => setSentModalOpen(true);
  const handleClose = () => setSentModalOpen(false);
  return (
    <div>
      <Head>
        <title>Lokkan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/negotiate.png" />
      </Head>

      <main className="section">
        <Navbar
          shape={false}
          loginOpen={loginOpen}
          setLoginOpen={setLoginOpen}
          handleLoginClose={handleLoginClose}
          handleLoginOpen={handleLoginOpen}
        />
        <Box>
          <Container maxWidth="md">
            <BaseStepper
              steps={steps}
              activeStep={activeStep}
              isStepSkipped={isStepSkipped}
              setActiveStep={setActiveStep}
              marginTop={"2vh"}
            />
            {activeStep === steps.length ? (
              <Container maxWidth="xs">
                <Fragment></Fragment>
              </Container>
            ) : (
              <Fragment>
                {activeStep === 0 ? (
                  <PersonalData handleNext={handleNext} />
                ) : activeStep === 1 ? (
                  <AddressData
                    handleNext={handleNext}
                    handleBack={handleBack}
                  />
                ) : (
                  <PerformanceData
                    handleNext={handleNext}
                    handleBack={handleBack}
                    handleOpen={handleOpen}
                    activeStep={activeStep}
                    steps={steps}
                  />
                )}
                <Grid
                  container
                  direction="row"
                  justifyContent={{
                    xs: "flex-start",
                    sm: "flex-start",
                    md: "flex-start",
                    lg: "flex-end",
                    xl: "flex-end",
                  }}
                  alignItems="center"
                  sx={{
                    // display: "flex",
                    // flexDirection: "row",

                    pt: 2,
                  }}
                >
                  {/* {activeStep !== 0 && (
                    <Button
                      color="inherit"
                      // disabled={activeStep === 0}
                      onClick={handleBack}
                      sx={{
                        mr: 1,
                        border: "1px solid #002152",
                        borderRadius: "4px",
                        px: 2,
                        py: 1,
                        color: "#002152",
                        fontSize: "16px",
                        fontWeight: "600",
                        lineHeight: "22px",
                        textTransform: "none",
                      }}
                    >
                      Come back
                    </Button>
                  )} */}

                  {/* {isStepOptional(activeStep) && (
                <Button
                  sx={{
                    mr: 1,
                    border: "1px solid #002152",
                    borderRadius: "4px",
                    px: 2,
                    py: 1,
                    color: "#002152",
                    fontSize: "16px",
                    fontWeight: "600",
                    lineHeight: "22px",
                    textTransform: "none",
                  }}
                  color="inherit"
                  onClick={handleSkip}
                >
                  Skip
                </Button>
              )} */}

                  {/* <Button
                    onClick={handleNext}
                    sx={{
                      background: "#7450F0",
                      borderRadius: "4px",
                      px: 2,
                      py: 1,
                      color: "#ffffff",
                      fontSize: "16px",
                      fontWeight: "600",
                      lineHeight: "22px",
                      textTransform: "none",
                      boxShadow: "0px 4px 8px rgba(81, 51, 182, 0.32)",
                      "&:hover": {
                        background: "#7450F0",
                        borderRadius: "4px",
                        px: 2,
                        py: 1,
                        color: "#ffffff",
                        fontSize: "16px",
                        fontWeight: "600",
                        lineHeight: "22px",
                        textTransform: "none",
                        boxShadow: "0px 4px 8px rgba(81, 51, 182, 0.32)",
                      },
                    }}
                  >
                    {activeStep === steps.length - 1
                      ? "Submit Proposal"
                      : "Next"}
                  </Button> */}
                </Grid>
              </Fragment>
            )}
          </Container>
          <BaseModal isShowing={sentModalOpen} isClose={handleClose}>
            <Tooltip title="Something">
              <>
                <BrokerRegistrationSentModal handleClose={handleClose} />
              </>
            </Tooltip>
          </BaseModal>
        </Box>
        <BrokerRegistrationFooter />
      </main>
    </div>
  );
}
