import { Box, Grid } from "@mui/material";
import React from "react";
import Navbar from "../src/component/shared/Navbar/Navbar";
import Footer from "../src/component/shared/Footer/Footer";
import Head from "next/head";
import categoryImage from "../public/Images/category.png";
import BlogCardUpper from "../src/component/blog/blogCardUpper/BlogCardUpper";
import blogLinkedIn from "../public/Images/blogLinkedin .png";
import blogWhatsapp from "../public/Images/blogWhatsapp.png";
import blogTwitter from "../public/Images/blogTwitter.png";
import blogFacebook from "../public/Images/blogFacebook.png";
import category_small from "../public/Images/category_small.png";
import Image from "next/image";
import CategoryUpperContent from "../src/component/category/categoryUpperContent/CategoryUpperContent";

function Category() {
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Navbar shape={false} paddingY={"1vh"} />
        <Grid
          container
          direction="column"
          justifyContent="center"
          alignItems="center"
          sx={{
            height: { xs: "40vh", sm: "40vh", md: "60vh" },
            width: { xs: "120%", sm: "120%", md: "100%" },
            backgroundImage: {
              xs: `url(${categoryImage.src})`,
              sm: `url(${categoryImage.src})`,
              md: `url(${categoryImage.src})`,
              lg: `url(${categoryImage.src})`,
              xl: `url(${categoryImage.src})`,
            },
          }}
        >
          <Box
            sx={{
              position: { lg: "absolute", xl: "absolute" },
            }}
          ></Box>
        </Grid>
        <Grid
          container
          direction="column"
          justifyContent="flex-start"
          alignItems="flex-start"
          sx={{ pl: 5, pt: 2 }}
        >
          <Box>
            <Image src={blogLinkedIn} alt="linkedin" />
          </Box>
          <Box>
            <Image src={blogWhatsapp} alt="whatsapp" />
          </Box>
          <Box>
            <Image src={blogFacebook} alt="linkedin" />
          </Box>
          <Box>
            <Image src={blogTwitter} alt="linkedin" />
          </Box>
        </Grid>
        <Box
          sx={{
            px: 25,
            position: { lg: "relative", xl: "relative" },
            top: -240,
          }}
        >
          <CategoryUpperContent />
        </Box>

        {/* <Box sx={{ mb: 2, px: 2 }}>
          <Typography
            variant="p"
            sx={{
              fontSize: "12px",
              fontWeight: "400",
              lineHeight: "28px",
              color: "#7450F0",
            }}
          >
            Highlights
          </Typography>
          <Divider sx={{ color: "#D3D3DF" }} />
        </Box>
        <Box sx={{ mx: 2, mb: 4 }}>
          <Grid container spacing={1}>
            {[0, 1, 2].map((data, index) => (
              <Grid item xs={12} sm={12} md={12} lg={4} xl={4} key={index}>
                <BlogHighlightsCard />
              </Grid>
            ))}
          </Grid>
        </Box>
        <Box sx={{ mb: 2, px: 2 }}>
          <Divider sx={{ color: "#D3D3DF" }} />
        </Box>
        <Grid
          container
          spacing={1}
          sx={{ mt: 2, pl: { xs: 1, sm: 2, md: 2, lg: 2, xl: 2 } }}
        >
          <Grid item xs={12} sm={12} md={12} lg={9} xl={9}>
            <Grid container spacing={1}>
              {[0, 1, 2, 3, 4, 5, 6, 7].map((data, index) => (
                <Grid key={index} item xs={12} sm={12} md={12} lg={6} xl={6}>
                  <SmallBlogCard />
                </Grid>
              ))}
            </Grid>
          </Grid>
          <Grid item xs={12} sm={12} md={12} lg={3} xl={3}>
            <MostAccess />
          </Grid>
        </Grid>
        <Stack spacing={2} sx={{ marginY: 8 }}>
          <Pagination count={5} variant="outlined" shape="rounded" />
        </Stack> */}
        <Footer />
      </main>
    </div>
  );
}

export default Category;
