import Navbar from "../src/component/shared/Navbar/Navbar";
import Footer from "../src/component/shared/Footer/Footer";
import shapeIcon from "../public/Images/eclipseShape.png";
import Head from "next/head";
import {
  Box,
  Grid,
  Typography,
  Container,
  ImageList,
  ImageListItem,
} from "@mui/material";
import FulfillDream from "../src/component/home/fullfill/FulfillDream";
import SideContent from "../src/component/home/FullfillSideContent/SideContent";
import SellSideContent from "../src/component/home/wantToSellSideContent/SellSideContent";
import mobileGray from "../public/Images/mobileGray.png";
import mobileBlue from "../public/Images/mobileBlue.png";
import WantSellSvgBackground from "../src/component/svg/WantSellSvgBackground";
import { renderToStaticMarkup } from "react-dom/server";
import WantToSell from "../src/component/home/wantToSell/WantToSell";
import BrokerRegisterContent from "../src/component/home/whoIsBroker/brokerRegister/BrokerRegisterContent";
import BrokerImageContent from "../src/component/home/whoIsBroker/brokerContent/BrokerImageContent";
import BestDealSvgBackground from "../src/component/svg/BestDealSvgBackground";
import HouseCard from "../src/component/reuseable/HouseCard/HouseCard";
import MobileSideContent from "../src/component/home/FullfillSideContent/mobileSideContent";
import BrokerImageContentMobile from "../src/component/home/whoIsBroker/brokerContent/BrokerImageContentMobile";
import BrokerHelp from "../src/component/IAmBroker/BrokerHelp/BrokerHelp";
import BrokerHelpContent from "../src/component/IAmBroker/BrokerHelp/BrokerHelpContent";
import BecomeBrokerContent from "../src/component/IAmBroker/BecomeBroker/BecomeBrokerContent";
import BecomeBroker from "../src/component/IAmBroker/BecomeBroker/BecomeBroker";
import CalulateComission from "../src/component/IAmBroker/MaxmizeResult/CalulateComission";
import ComissionResult from "../src/component/IAmBroker/MaxmizeResult/ComissionResult";
import BrokerFacilities from "../src/component/IAmBroker/BrokerFacilities/BrokerFacilities";
import advertiseImage from "../public/Images/advertise.png";
import wantImageMobile from "../public/Images/mobileWant.png";
import trackImage from "../public/Images/track.png";
import digitalImage from "../public/Images/digital.png";
import fastImage from "../public/Images/fast.png";
import PropertyList from "../src/component/IAmOwner/propertyList/PropertyList";
import dynamic from "next/dynamic";
const BaseGoogleMap = dynamic(
  () => import("../src/component/IAmOwner/map/BaseGoogleMap"),
  {
    ssr: false,
  }
);

const advertiseData = [
  {
    name: "Practicality",
    info: "Advertise your property and find out about everything that happens through the application.",
  },
  {
    name: "100% digital",
    info: "100% digital buying and selling process (scheduling visits, proposals, contracts, certificates, public deed)",
  },
  {
    name: "Documentation and digital signature",
    info: "Contract, registrations, certificates, consultations (SERASA, SPC - seller) with a click. Elaboration and signature of the deed digitally (without having to go to the notary).",
  },
  {
    name: "Fast selling process",
    info: "Receive the down payment right after the analysis of the documents. Fastest sales process on the market.",
  },
];

const PracticalData = [
  {
    name: "track everything online",
    info: "Announcements, schedules of visits and proposals all in the palm of your hands",
    imageSrc: trackImage,
  },
  {
    name: "100% digital processes",
    info: "Signing of contracts, issuance of certificates, documents and even public deed of purchase and sale, all digitally, without leaving home",
    imageSrc: digitalImage,
  },
  {
    name: "Fast sale!",
    info: "Fastest sales process on the market",
    imageSrc: fastImage,
  },
];

export default function Advertise(props) {
  const svgString = encodeURIComponent(
    renderToStaticMarkup(<WantSellSvgBackground />)
  );
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Navbar shape={false} />
        <Grid container sx={{ px: 3, py: 2, background: "#F9F9FB" }}>
          <Grid item xs={8}>
            <PropertyList />
          </Grid>
          <Grid item xs={4}>
            {/* <BaseGoogleMap /> */}
          </Grid>
        </Grid>
      </main>
    </div>
  );
}
