import Navbar from "../src/component/shared/Navbar/Navbar";
import Head from "next/head";
import {
  Box,
  Grid,
  Typography,
  Container,
  ImageList,
  ImageListItem,
  Button,
} from "@mui/material";
import orionImage from "../public/Images/orion_view.svg";
import Image from "next/image";
import TabView from "../src/component/PropertyView/tab/TabView";

export default function Advertise(props) {
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Navbar shape={false} paddingY={"1vh"} />
        <Box sx={{ ml: 3 }}>
          <Grid
            container
            direction="row"
            justifyContent="flex-start"
            alignItems="flex-start"
          >
            <Button sx={{ display: "flex", color: "#1A1859" }}>
              <Image src={orionImage} alt="orionImage" />
              <Typography
                variant="p"
                sx={{ fontSize: "24px", fontWeight: 700, color: "#1A1859" }}
              >
                Rua Carlos Vicari | Água Branca São Paulo - SP
              </Typography>
            </Button>
          </Grid>
          <Grid
            container
            direction="row"
            justifyContent="flex-start"
            alignItems="flex-start"
            sx={{ marginTop: 1 }}
          >
            <TabView />
          </Grid>
        </Box>
      </main>
    </div>
  );
}
