import {
  Box,
  Button,
  Container,
  Grid,
  InputAdornment,
  TextField,
  Typography,
} from "@mui/material";
import Head from "next/head";
import registerImage from "../public/Images/register.png";
import GoogleIcon from "@mui/icons-material/Google";
import FacebookOutlinedIcon from "@mui/icons-material/FacebookOutlined";
import ArrowBackIosNewOutlinedIcon from "@mui/icons-material/ArrowBackIosNewOutlined";
import Image from "next/image";
import Link from "next/link";
import BaseTextField from "../src/component/reuseable/baseTextField/BaseTextField";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import NoEncryptionOutlinedIcon from "@mui/icons-material/NoEncryptionOutlined";
import React, { useState } from "react";
import { useForm, Controller } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as Yup from "yup";
import BaseOutlinedPhoneInput from "../src/component/reuseable/baseOutlinedPhoneInput/BaseOutlinedPhoneInput";

const validationSchema = Yup.object().shape({
  name: Yup.string().required("Name is required"),
  phone: Yup.string().required("Phone is required"),
  email: Yup.string()
    .required("Email is required")
    .matches(/.+@.+\.[A-Za-z]+$/, "Email is invalid"),
  password: Yup.string()
    .required("Password is required")
    .min(6, "Password must be at least 6 characters")
    .max(40, "Password must not exceed 40 characters"),
});

const UserRoleData = [
  {
    name: "Buyer",
    value: 4,
  },
  {
    name: "Owner",
    value: 3,
  },
];

export default function Registration() {
  const [activeBtn, setActiveBtn] = useState(4);
  const [showPass, setShowPass] = React.useState(false);
  const handleClickShowPassword = () => {
    setShowPass(!showPass);
  };

  return (
    <div>
      <Head>
        <title>Lokkan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/negotiate.png" />
      </Head>

      <main className="section">
        <Box sx={{ px: 5 }}>
          <Grid container spacing={1}>
            <Grid item xs={12} sm={12} md={12} lg={4} xl={4}>
              <Grid
                container
                direction="column"
                justifyContent="flex-start"
                alignItems="flex-start"
                sx={{ py: 4 }}
              >
                <Link href="/">
                  <a
                    style={{
                      textDecoration: "none",
                      listStyle: "none",
                      width: "100%",
                    }}
                  >
                    <Button sx={{ textTransform: "none" }}>
                      <ArrowBackIosNewOutlinedIcon sx={{ color: "#7450F0" }} />
                      <Typography
                        variant="p"
                        sx={{
                          color: "#7450F0",
                          fontSize: "14px",
                          fontWeight: "600",
                          lineHeight: "17px",
                        }}
                      >
                        Cancel Registration
                      </Typography>
                    </Button>
                  </a>
                </Link>
                <Container maxWidth="xs">
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 8, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Name<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <BaseTextField
                    fullWidth
                    size={"small"}
                    placeholder={"Name"}
                  />
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Email<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <BaseTextField
                    fullWidth
                    size={"small"}
                    placeholder={"Email"}
                  />
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Phone<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <BaseOutlinedPhoneInput
                    size={"small"}
                    placeholder={"Phone"}
                  />
                  {/* <BaseTextField
                    fullWidth
                    size={"small"}
                    placeholder={"Phone"}
                    type={"number"}
                  /> */}
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Password<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <BaseTextField
                    fullWidth
                    size={"small"}
                    placeholder={"Password"}
                    type={showPass ? "text" : "password"}
                    InputProps={{
                      endAdornment: (
                        <InputAdornment
                          sx={{ cursor: "pointer" }}
                          position="end"
                          onClick={handleClickShowPassword}
                        >
                          {showPass ? (
                            <NoEncryptionOutlinedIcon />
                          ) : (
                            <LockOutlinedIcon />
                          )}
                        </InputAdornment>
                      ),
                    }}
                  />

                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Profile
                    </Typography>
                  </Grid>
                  <Grid
                    container
                    // direction="row"
                    // justifyContent="flex-start"
                    // alignItems="flex-start"
                    // gap={2}
                    spacing={1}
                  >
                    {UserRoleData?.map((data, index) => (
                      <Grid item xs={4} key={index}>
                        <Button
                          onClick={() => setActiveBtn(data.value)}
                          sx={{
                            width: "100%",
                            background: `${
                              activeBtn === data.value ? "#0362F0" : "#F2F5F6"
                            }`,
                            borderRadius: "152px",
                            color: `${
                              activeBtn === data.value ? "#ffffff" : "#002152"
                            }`,
                            fontSize: {
                              xs: "12px",
                              sm: "13px",
                              md: "16px",
                              lg: "13px",
                              xl: "16px",
                            },
                            fontWeight: "400",
                            lineHeight: "22px",
                            textTransform: "none",
                            px: { xs: 0, sm: 2, md: 2, lg: 2, xl: 2 },
                            py: 1,
                            "&:hover": {
                              width: "100%",
                              background: "#0362F0",
                              borderRadius: "152px",
                              color: "#ffffff",
                              fontSize: {
                                xs: "12px",
                                sm: "13px",
                                md: "16px",
                                lg: "13px",
                                xl: "16px",
                              },
                              fontWeight: "400",
                              lineHeight: "22px",
                              textTransform: "none",
                              px: { xs: 0, sm: 2, md: 2, lg: 2, xl: 2 },
                              py: 1,
                            },
                          }}
                        >
                          {data.name}
                        </Button>
                      </Grid>
                    ))}

                    <Grid item xs={4}>
                      <Link href="/broker_registration">
                        <Button
                          onClick={() => setActiveBtn(2)}
                          sx={{
                            width: "100%",
                            background: `${
                              activeBtn === 2 ? "#0362F0" : "#F2F5F6"
                            }`,
                            borderRadius: "152px",
                            color: `${activeBtn === 2 ? "#ffffff" : "#002152"}`,
                            borderRadius: "152px",

                            fontSize: {
                              xs: "12px",
                              sm: "13px",
                              md: "16px",
                              lg: "13px",
                              xl: "16px",
                            },
                            fontWeight: "400",
                            lineHeight: "22px",
                            textTransform: "none",
                            px: { xs: 0, sm: 2, md: 2, lg: 2, xl: 2 },
                            py: 1,
                            "&:hover": {
                              width: "100%",
                              background: "#0362F0",
                              borderRadius: "152px",
                              color: "#ffffff",
                              fontSize: {
                                xs: "12px",
                                sm: "13px",
                                md: "16px",
                                lg: "13px",
                                xl: "16px",
                              },
                              fontWeight: "400",
                              lineHeight: "22px",
                              textTransform: "none",
                              px: { xs: 0, sm: 2, md: 2, lg: 2, xl: 2 },
                              py: 1,
                            },
                          }}
                        >
                          Broker
                        </Button>
                      </Link>
                    </Grid>
                  </Grid>
                  <Link href="/broker_registration">
                    <a
                      style={{
                        textDecoration: "none",
                        listStyle: "none",
                        width: "100%",
                      }}
                    >
                      <Button
                        fullWidth
                        sx={{
                          background:
                            "linear-gradient(270deg, #1DEECB 1.2%, #00C1B4 98.7%)",
                          boxShadow: "0px 4px 34px rgba(0, 0, 0, 0.08)",
                          borderRadius: "4px",
                          color: "#ffffff",
                          fontSize: "16px",
                          lineHeight: "22px",
                          fontWeight: "600",
                          mt: 3,
                          textTransform: "none",
                          py: 1,
                        }}
                      >
                        register
                      </Button>
                    </a>
                  </Link>
                  <Grid
                    container
                    direction="row"
                    justifyContent="center"
                    alignItems="center"
                    sx={{ height: "8vh" }}
                  >
                    Or
                  </Grid>
                  <Grid container spacing={1}>
                    <Grid item xs={12} sm={12} md={12} lg={6} xl={6}>
                      <Button
                        sx={{
                          display: "flex",
                          background: "#DC4C3F",
                          borderRadius: "4px",
                          textTransform: "none",
                          px: 2,
                          py: 1,
                          width: "100%",
                          "&:hover": {
                            background: "#DC4C3F",
                            borderRadius: "4px",
                            textTransform: "none",
                            px: 2,
                            py: 1,
                            width: "100%",
                          },
                        }}
                      >
                        <GoogleIcon sx={{ color: "#ffffff" }} />
                        <Typography
                          sx={{
                            color: "#ffffff",
                            fontSize: {
                              xs: "12px",
                              sm: "12px",
                              md: "12px",
                              lg: "12px",
                              xl: "12px",
                              xxl: "14px",
                            },
                            lineHeight: "17px",
                            fontWeight: "400",
                          }}
                        >
                          Login with Gmail
                        </Typography>
                      </Button>
                    </Grid>
                    <Grid item xs={12} sm={12} md={12} lg={6} xl={6}>
                      <Button
                        sx={{
                          display: "flex",
                          background: "#4469B0",
                          borderRadius: "4px",
                          textTransform: "none",
                          px: 2,
                          py: 1,
                          width: "100%",
                          "&:hover": {
                            background: "#4469B0",
                            borderRadius: "4px",
                            textTransform: "none",
                            px: 2,
                            py: 1,
                            width: "100%",
                          },
                        }}
                      >
                        <FacebookOutlinedIcon sx={{ color: "#ffffff" }} />
                        <Typography
                          sx={{
                            color: "#ffffff",
                            fontSize: {
                              xs: "12px",
                              sm: "12px",
                              md: "12px",
                              lg: "12px",
                              xl: "12px",
                              xxl: "14px",
                            },
                            lineHeight: "17px",
                            fontWeight: "400",
                          }}
                        >
                          Login with Facebook
                        </Typography>
                      </Button>
                    </Grid>
                  </Grid>
                </Container>
              </Grid>
            </Grid>
            <Grid item xs={12} sm={12} md={12} lg={8} xl={8}>
              <Box>
                <Image src={registerImage} alt="register" />
              </Box>
            </Grid>
          </Grid>
        </Box>
      </main>
    </div>
  );
}
