import {
  Box,
  Button,
  Container,
  Grid,
  TextField,
  Typography,
} from "@mui/material";
import Head from "next/head";
import registerImage from "../public/Images/register.png";
import Image from "next/image";

export default function Registration(props) {
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Box sx={{ px: 5, height: "100vh" }}>
          <Grid container spacing={1}>
            <Grid item xs={4}>
              <Grid
                container
                direction="column"
                justifyContent="flex-start"
                alignItems="flex-start"
                sx={{ py: 4 }}
              >
                <Typography
                  variant="p"
                  sx={{
                    color: "#7450F0",
                    fontSize: "14px",
                    fontWeight: "600",
                    lineHeight: "17px",
                  }}
                >
                  {"<"} cancel registration
                </Typography>
                <Container maxWidth="xs">
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Name<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <TextField
                    fullWidth
                    size="small"
                    id="outlined-basic"
                    placeholder="Name"
                    variant="outlined"
                  />
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Email<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <TextField
                    fullWidth
                    size="small"
                    id="outlined-basic"
                    placeholder="Email"
                    variant="outlined"
                  />
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Phone<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <TextField
                    fullWidth
                    size="small"
                    id="outlined-basic"
                    placeholder="Phone"
                    variant="outlined"
                  />
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Password<span style={{ color: "#E63333" }}>*</span>
                    </Typography>
                  </Grid>
                  <TextField
                    fullWidth
                    size="small"
                    id="outlined-basic"
                    placeholder="Password"
                    variant="outlined"
                  />

                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{ mt: 3, mb: 1 }}
                  >
                    <Typography
                      variant="p"
                      sx={{
                        color: "#253858",
                        fontSize: "14px",
                        fontWeight: "400",
                        lineHeight: "16px",
                      }}
                    >
                      Profile
                    </Typography>
                  </Grid>
                  <Grid
                    container
                    direction="row"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    gap={2}
                  >
                    <Button
                      sx={{
                        background: "#0362F0",
                        borderRadius: "152px",
                        color: "#ffffff",
                        textTransform: "none",
                        px: 2,
                        py: 1,
                      }}
                    >
                      Physical Person
                    </Button>
                    <Button
                      sx={{
                        background: "#F2F5F6",
                        borderRadius: "152px",
                        color: "#002152",
                        textTransform: "none",
                        px: 2,
                        py: 1,
                      }}
                    >
                      Broker
                    </Button>
                  </Grid>
                </Container>
              </Grid>
            </Grid>
            <Grid item xs={8}>
              <Image src={registerImage} alt="register" />
            </Grid>
          </Grid>
        </Box>
      </main>
    </div>
  );
}
