import {
  Box,
  Container,
  Grid,
  ImageList,
  ImageListItem,
  Typography,
} from "@mui/material";
import React from "react";
import Navbar from "../src/component/shared/Navbar/Navbar";
import Footer from "../src/component/shared/Footer/Footer";
import Head from "next/head";
import categoryImage from "../public/Images/category.png";
import BlogCardUpper from "../src/component/blog/blogCardUpper/BlogCardUpper";
import blogLinkedIn from "../public/Images/blogLinkedin .png";
import blogWhatsapp from "../public/Images/blogWhatsapp.png";
import blogTwitter from "../public/Images/blogTwitter.png";
import blogFacebook from "../public/Images/blogFacebook.png";
import category_small from "../public/Images/category_small.png";
import Image from "next/image";
import CategoryUpperContent from "../src/component/category/categoryUpperContent/CategoryUpperContent";
import CategoryImageContent from "../src/component/category/categoryImageContent/CategoryImageContent";
import blue_facebook from "../public/Images/blue_facebook.png";
import blue_twitter from "../public/Images/blue_twitter.png";
import blue_linkedin from "../public/Images/blue_linkedin.png";
import blue_whatsapp from "../public/Images/blue_whatsapp.png";
import CategorySubscribe from "../src/component/category/categorySubscribe/CategorySubscribe";
import BlogHighlightsCard from "../src/component/blog/blogHighlightsCard/BlogHighlightsCard";
import PrivacyContent from "../src/component/privacy/privacyContent/PrivacyContent";

function UserManual() {
  return (
    <div>
      <Head>
        <title>Real Estate App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <Navbar shape={false} paddingY={"1vh"} />
        <Grid
          container
          direction="column"
          justifyContent="center"
          alignItems="center"
          sx={{
            height: { xs: "25vh", sm: "25vh", md: "25vh" },
            // width: { xs: "120%", sm: "120%", md: "100%" },
            background: "linear-gradient(90deg, #20BAF6 0%, #7450F0 100%)",
          }}
        >
          <Box
            sx={{
              position: { lg: "absolute", xl: "absolute" },
            }}
          ></Box>
        </Grid>

        <Box
          sx={{
            px: { xs: 2, sm: 2, md: 2, lg: 25, xl: 25 },
            position: { lg: "relative", xl: "relative" },
            top: -120,
          }}
        >
          <PrivacyContent name="User manual" />
        </Box>

        <Footer />
      </main>
    </div>
  );
}

export default UserManual;
