import Head from "next/head";
import { Box, CircularProgress, Container, Grid, Tooltip } from "@mui/material";
import { useRouter } from "next/router";
import { emailVerifyApi, userDetailsApi } from "@/api";
import { signIn } from "next-auth/react";
import { useEffect } from "react";

export default function UserLoading() {
  const router = useRouter();
  const { query } = router;

  useEffect(() => {
    const getData = async () => {
      if (query?.token) {
        const [err, resp] = await emailVerifyApi(query?.token);
        if (!err) {
          localStorage.setItem("token", resp?.data?.token);
          const [error, response] = await userDetailsApi();

          if (!error) {
            return signIn("credentials", {
              userId: response?.data?.user?.id,
              userEmail: response?.data?.user?.email,
              name: response?.data?.user?.name,
              phone: response?.data?.user?.phone,
              status: response?.data?.user?.status,
              role: response?.data?.user?.roles[0]?.slug,
              roleId: response?.data?.user?.roles[0]?.id,
              userImage: response?.data?.user?.attachments[0]?.file_path,
              // image: response?.data?.user?.attachments[0],
              // permissions: JSON.stringify(
              //   response?.data?.user?.roles[0]?.permissions
              // ),
              callbackUrl: "/my-properties",
            });
          } else {
            router.push("/");
          }
        }
      } else {
        return;
      }
    };
    getData();
  }, [query?.token, router]);

  return (
    <div>
      <Head>
        <title>Lokkan - A imobiliária digital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/negotiate.png" />
      </Head>

      <main className="section">
        <Container maxWidth="md" sx={{ px: 2, py: 0 }}>
          <Grid
            container
            direction="row"
            justifyContent="center"
            alignItems="center"
            sx={{ height: "100vh" }}
          >
            <CircularProgress size="8rem" />
          </Grid>
        </Container>
      </main>
    </div>
  );
}
