import Head from "next/head";
import Image from "next/image";
import PropTypes from "prop-types";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import ResponsiveDrawer from "../src/component/sharedProposal/ResponsiveDrawer/ResponsiveDrawer";
import { Button, Container, Grid, InputBase, Paper } from "@mui/material";
import { useState } from "react";
import Releases from "../src/component/properties/Releases/Releases";
import ThirdTab from "../src/component/properties/Third/ThirdTab";
import NewRegistration from "../src/component/properties/NewRegistration/NewRegistration";
import notifyImage from "../public/Images/notify.png";
import BasicBreadcrumbs from "../src/component/reuseable/baseBreadCrumb/BaseBreadCrumb";
import ArrowBackIosNewOutlinedIcon from "@mui/icons-material/ArrowBackIosNewOutlined";
import Link from "next/link";
import searchIcon from "../public/Images/SearchBlack.png";
import RentCard from "../src/component/reuseable/rentCard/RentCard";

const drawerWidth = 240;

const BreadCrumbsData = [
  { stage: "Start", route: "" },
  { stage: "My properties", route: "" },
];

const style = {
  ml: { xs: 4, sm: 4, md: 0, lg: 0, xl: 0 },
  mt: { xs: 1, sm: 1, md: 0, lg: 0, xl: 0 },
};

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Box>{children}</Box>
        </Box>
      )}
    </div>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function a11yProps(index) {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
}

export default function ViewProperties(props) {
  const [value, setValue] = useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box sx={{ display: "flex" }}>
          <ResponsiveDrawer />
          <Box
            sx={{
              //   backgroundColor: "#f6f8fc",
              flexGrow: 1,
              background: "#F2F5F6",
              minHeight: "100vh",
              width: { sm: `calc(100% - ${drawerWidth}px)` },
              paddingX: { xs: 0, sm: 0, md: 6, lg: 6, xl: 6 },
              paddingTop: { xs: 6, sm: 6, md: 6, lg: 8, xl: 3 },
              paddingBottom: { xs: 3, sm: 3, md: 3, lg: 4, xl: 3 },
            }}
          >
            <Grid
              container
              direction="row"
              justifyContent="space-between"
              alignItems="flex-start"
            >
              <BasicBreadcrumbs
                BreadcrumbsData={BreadCrumbsData}
                lastStageData={"aston"}
                style={style}
              />
              <Image src={notifyImage} alt="notify" />
            </Grid>

            <Grid
              container
              spacing={1}
              //   direction="row"
              //   justifyContent="space-between"
              //   alignItems="flex-start"
              sx={{ mt: 1 }}
            >
              <Grid item xs={12} sm={12} md={12} lg={2} xl={2}>
                <Link href="/my_properties">
                  <a
                    style={{
                      textDecoration: "none",
                      listStyle: "none",
                      width: "100%",
                    }}
                  >
                    <Button sx={{ textTransform: "none" }}>
                      <ArrowBackIosNewOutlinedIcon sx={{ color: "#7450F0" }} />
                      <Typography
                        variant="p"
                        sx={{
                          color: "#7450F0",
                          fontSize: "14px",
                          fontWeight: "600",
                          lineHeight: "17px",
                        }}
                      >
                        come back
                      </Typography>
                    </Button>
                  </a>
                </Link>
              </Grid>
              <Grid item xs={0} sm={0} md={0} lg={2} xl={4}></Grid>

              <Grid
                item
                xs={12}
                sm={12}
                md={12}
                lg={4}
                xl={4}
                sx={{ mx: { xs: 2, sm: 2, md: 0 } }}
              >
                <Paper
                  component="form"
                  sx={{
                    // p: "2px 4px",
                    display: "flex",
                    alignItems: "center",
                    // border: "1px solid red",
                    boxShadow: "none",
                    border: "1px solid #D3D3DF",
                    borderRadius: "4px",

                    width: {
                      xs: "100%",
                      sm: "100%",
                      md: "100%",
                      xl: "100%",
                      lg: "100%",
                    },
                  }}
                >
                  <Grid sx={{ paddingRight: 2, width: "100%" }}>
                    {/* <IconButton sx={{ p: "10px" }} aria-label="menu">
          <MenuIcon />
        </IconButton> */}
                    <InputBase
                      fullWidth
                      sx={{ ml: 1, flex: 1 }}
                      placeholder="search.."
                      inputProps={{
                        "aria-label": "search google maps",
                        style: {
                          color: "#9F9FA9",
                          fontSize: "20px",
                        },
                      }}
                    />
                  </Grid>
                  <Box
                    sx={{
                      padding: "1vh",
                    }}
                  >
                    <Image src={searchIcon} alt="search" />
                  </Box>
                </Paper>
              </Grid>
              <Grid
                item
                xs={12}
                sm={12}
                md={12}
                lg={4}
                xl={2}
                sx={{ mx: { xs: 2, sm: 2, md: 0 } }}
              >
                <Button
                  sx={{
                    textTransform: "none",
                    background: "#0362F0",
                    borderRadius: "4px",
                    color: "#ffffff",
                    fontSize: "16px",
                    fontWeight: "600",

                    width: {
                      xs: "100%",
                      sm: "100%",
                      md: "100%",
                      lg: "100%",
                      xl: "100%",
                    },
                  }}
                >
                  New property
                </Button>
              </Grid>
            </Grid>
            <Box sx={{ mt: 4, mx: { xs: 2, sm: 2, md: 0 } }}>
              <Grid container spacing={4}>
                {[0, 1, 2].map((data, index) => (
                  <Grid
                    key={index}
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={6}
                    xl={6}
                    xxl={6}
                  >
                    <RentCard />
                  </Grid>
                ))}
              </Grid>
            </Box>
          </Box>
        </Box>
      </main>
    </div>
  );
}
