export const FEATURE_REQUEST = "FEATURE_REQUEST";
export const FEATURE_SUCCESS = "FEATURE_SUCCESS";
export const FEATURE_FAILED = "FEATURE_FAILED";

export const FEATURE_CREATE_LOADING = "FEATURE_CREATE_LOADING";
export const FEATURE_CREATE_SUCCESS = "FEATURE_CREATE_SUCCESS";
export const FEATURE_CREATE_FAILED = "FEATURE_CREATE_FAILED";
