export const CONTACT_DETAILS_REQUEST = "CONTACT_DETAILS_REQUEST";
export const CONTACT_DETAILS_SUCCESS = "CONTACT_DETAILS_SUCCESS";
export const CONTACT_DETAILS_FAILED = "CONTACT_DETAILS_FAILED";

export const CONTACT_DETAILS_SIGNATURE_CREATE =
  "CONTACT_DETAILS_SIGNATURE_CREATE";
export const CONTACT_DETAILS_SIGNATURE_UPDATE =
  "CONTACT_DETAILS_SIGNATURE_UPDATE";
